Teachers&Courses/Teachers&Courses/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('first_app.urls')),
]

Teachers&Courses/first_app/urls.py
from django.urls import path
from . import views

app_name = 'first_app'
urlpatterns = [
    path('', views.index),
    path('registration', views.registration,
         name='registration'),
    path('login', views.login,
         name='login'),
    path('logout', views.logout,
         name='logout'),
    path('home', views.success, name='home'),
    path('courses/new', views.newCourse, name='newCourse'),
    path('courseCreate', views.courseCreate,
         name='courseCreate'),
    path('newCourseRedirect', views.newCourseRedirect,
         name='newCourseRedirect'),
    path('successRedirect', views.successRedirect,
         name='successRedirect'),
    path('courses/<int:id>', views.courseDetails, name='courseDetails'),
    path('courses/<int:course_id>/edit', views.courseEdit, name='courseEdit'),
    path('editCourse/<int:course_id>', views.editCourse,
         name='editCourse'),
    path('deleteCourse/<int:course_id>/', views.deleteCourse, name='deleteCourse'),
    path('add_student/<int:course_id>/',
         views.addStudent, name='addStudent'),

]

Teachers&Courses/first_app/models.py
from django.db import models
import re


class TeacherManager(models.Manager):
    def login_validator(self, postData):
        error = {}
        get_emails = Teacher.objects.all()
        if len(postData['teacher_name']) < 2:
            error['teacher_name'] = "teacher name 2 characters or more"

        EMAIL_REGEX = re.compile(
            r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(postData['email']):
            error['email'] = "nnvalid email address!"

        for teacher in get_emails:
            if postData['email'] == teacher.email:
                error['email_exists'] = "email exists"

        if postData['password'] != postData['conf_password']:
            error['password_conf'] = " confirmation password not matched"

        if len(postData['password']) < 8:
            error['password'] = "password Must be at least 8 characters"
        return error

    def course_validator(self, postData):
        error = {}
        days_list = ['saturday', 'monday',
                     'tuesday', 'wednesday', 'thursday']
        day_exist = False
        if len(postData['course_name']) < 2:
            error['course_name'] = "course name 2 characters or more"
        if len(postData['teaching_level']) < 1:
            error['teaching_level_empty'] = "teaching level required"
        elif int(postData['teaching_level']) > 3 or int(postData['teaching_level']) <= 0:
            error['teaching_level_range'] = "teaching level between 1 to 3"

        lecture_day = postData['lecture_day']
        for day in days_list:
            if lecture_day == day:
                day_exist = True
                break
        if not day_exist:
            error['lecture_day'] = "please enter a day name "
        return error

    def validate_student(self, postData, course_id):
        error = {}
        if len(postData['student_name']) < 2:
            error['student_name'] = "students Name 2 characters or more"
        course = Course.objects.get(id=course_id)
        if course.students.all().count() >= 25:
            error['student_number'] = " Maximum number of students in 25"
        return error


class Teacher(models.Model):
    teacher_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # courses
    objects = TeacherManager()


class Course(models.Model):
    course_name = models.CharField(max_length=255)
    teaching_level = models.SmallIntegerField()
    lecture_day = models.CharField(max_length=255)
    teacher = models.ForeignKey(Teacher, related_name='courses',
                             on_delete=models.CASCADE)
    objects = TeacherManager()
    # students


class Student(models.Model):
    student_name = models.CharField(max_length=255)
    course = models.ForeignKey(
        Course, related_name='students', on_delete=models.CASCADE)
    objects = TeacherManager()

Teachers&Courses/first_app/views.py
from django.shortcuts import render, redirect
from first_app.models import *
from django.contrib import messages
import bcrypt


def index(request):
    return render(request, 'index.html')


def registration(request):
    error = Teacher.objects.login_validator(request.POST)
    if len(error) > 0:
        for key, value in error.items():
            messages.error(request, value)
        return redirect('/')
    else:
        password = request.POST['password']
        ps_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
        Teacher.objects.create(
            teacher_name=request.POST['teacher_name'], email=request.POST['email'], password=ps_hash
        )
        messages.success(request, "Teacher has been created Successfully!")
        return redirect('/')


def login(request):
    teacher = Teacher.objects.filter(email=request.POST['email'])
    if teacher:
        logged_teacher = teacher[0]
        if bcrypt.checkpw(request.POST['password'].encode(), logged_teacher.password.encode()):
            request.session['teacher_id'] = logged_teacher.id
            messages.success(request, " logged in")
            return redirect('/home')
        else:
            messages.error(request, "email / password incorrect")
            return redirect('/')
    else:
        messages.error(request, "email / password incorrect")
        return redirect('/')


def successRedirect(request):
    list(messages.get_messages(request))
    return redirect('/home')


def success(request):
    teacher = Teacher.objects.get(id=request.session['teacher_id'])
    course = Course.objects.all()
    context = {
        'teacher_object': teacher,
        'course_object': course,
        'teacher_session': request.session['teacher_id'],
    }
    return render(request, 'home.html', context)


def logout(request):
    list(messages.get_messages(request))
    request.session.flush()
    return redirect('/')


def newCourse(request):
    return render(request, 'new_course.html')


def newCourseRedirect(request):
    list(messages.get_messages(request))
    return redirect('/courses/new')


def courseCreate(request):
    error = Course.objects.course_validator(request.POST)
    if len(error) > 0:
        for key, value in error.items():
            messages.error(request, value)
        return redirect('/courses/new')
    else:
        teacher = Teacher.objects.get(id=request.session['teacher_id'])
        Course.objects.create(
            course_name=request.POST['course_name'], teaching_level=request.POST['teaching_level'], lecture_day=request.POST['lecture_day'].capitalize(), teacher=teacher
        )
        return redirect('/successRedirect')


def courseDetails(request, id):
    teacher = Teacher.objects.get(id=request.session['teacher_id'])
    course = Course.objects.get(id=id)
    student_obj = course.students.all()
    print(student_obj)
    context = {
        'current_teacher': teacher,
        'course_object': course,
        'student_object': student_obj,
        'teacher_session': request.session['teacher_id'],

    }
    return render(request, 'course_details.html', context)


def editCourse(request, course_id):
    error = Course.objects.course_validator(request.POST)
    if len(error) > 0:
        for key, value in error.items():
            messages.error(request, value)
        return redirect('/courses/' + str(course_id) + '/edit')

    course = Course.objects.get(id=course_id)
    course.course_name = request.POST['course_name']
    course.teaching_level = request.POST['teaching_level']
    course.lecture_day = request.POST['lecture_day']
    course.save()

    return redirect('/successRedirect')


def deleteCourse(request, course_id):
    course = Course.objects.get(id=course_id)
    course.delete()
    return redirect('/successRedirect')


def courseEdit(request, course_id):
    teacher = Teacher.objects.get(id=request.session['teacher_id'])
    course = Course.objects.get(id=course_id)

    context = {
        'current_teacher': teacher,
        'course_object': course,
        'teacher_session': request.session['teacher_id']

    }
    return render(request, 'courseEdit.html', context)


def addStudent(request, course_id):
    error = Student.objects.validate_student(request.POST, course_id)
    if len(error) > 0:
        for key, value in error.items():
            messages.error(request, value)
        return redirect('/courses/' + str(course_id))
    course = Course.objects.get(id=course_id)
    Student.objects.create(student_name=request.POST['student_name'], course=course)
    return redirect('/courses/' + str(course_id))

Teachers&Courses/first_app/templates/courseEdit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>COURSE EDIT</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <div class="container mt-6 mb-3" style="background-color: white;">
        {% if messages %}
        <div class="row justify-content-center mt-3">
            <div class="col-sm-12">
                {% for massage in messages %}
                {% if massage.tags == 'error' %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <h4>Warring ! :</h4> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% if massage.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <h4>Success ! :</h4> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if current_teacher.id == course_object.teacher.id %}
        <div class="row"> 
            <div class="col-sm-12  mt-3 mb-2 ">
                <h2>{{course_object.course_name}}</h2>
            </div>
            <div class="row mb-2">
                <div class="col-sm-12">
                    <a href="{% url 'first_app:successRedirect' %}"> Dashboard </a>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-sm-6 ">
                    <form action="{% url 'first_app:editCourse' course_id=course_object.id %}" method="post">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Course Name:</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="text" name="Course_name" class="form-control" value="{{course_object.Course_name}}">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Teaching Level :</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="number" name="teaching_level" class="form-control" value="{{course_object.teaching_level}}">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Lecture Day:</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="text" name="lecture_day" class="form-control" value="{{course_object.lecture_day}}">
                            </div>
                            
                        </div>
                        
                        <div class="row mb-3 justify-content-center">
                            <div class="col-sm-6 d-flex justify-content-around">
                                <a href="{% url 'first_app:deleteCourse' course_id=course_object.id %}" class="btn btn-danger">Delete</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% else %}
        <div class="row"> 
            <div class="col-sm-12  mt-3 mb-2 ">
                <h2>{{course_object.course_name}}</h2>
            </div>
            <div class="row mb-2">
                <div class="col-sm-12">
                    <a href="{% url 'first_app:successRedirect' %}"> Dashboard </a>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-sm-6 ">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Course Name:</label>
                            </div>
                            <div class="col-sm-6">
                                <label class="col-form-label" for=""><h4>{{course_object.course_name}}</h4></label>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Teaching Level:</label>
                            </div>
                            <div class="col-sm-6">
                                <label class="col-form-label" for=""><h4>{{course_object.teaching_level}}</h4></label>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Lecture Day:</label>
                            </div>
                            <div class="col-sm-6">
                                <label class="col-form-label" for=""><h4>{{course_object.lecture_day}}</h4></label>
                            </div>
                            
                        </div>

                </div>
            </div>
        </div>
        {% endif %}

    </div>
    </div>



</body>


</html>

Teachers&Courses/first_app/templates/course_details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>COURSE DETAILS</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <div class="container mt-6 mb-3" style="background-color: white;">
        {% if teacher_session %} 
        
        {% if messages %}
        <div class="row justify-content-center mt-3">
            <div class="col-sm-12">
                {% for massage in messages %}
                {% if massage.tags == 'error' %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <h4>Warring ! :</h4> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% if massage.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <h4>Success ! :</h4> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endif %}


        <div class="row">
            <div class="col-sm-12  mt-3 mb-2 ">
                <h2>{{course_object.course_name}} </h2>
            </div>
            <div class="row mb-2">
                <div class="col-sm-12">
                    <a href="{% url 'first_app:successRedirect' %}"> Dashboard </a>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-sm-6 ">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Course Name:</label>
                        </div>
                        <div class="col-sm-6">
                            <label class="col-form-label" for=""><h4>{{course_object.course_name}}</h4></label>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Teaching Level (1-5):</label>
                        </div>
                        <div class="col-sm-6">
                            <label class="col-form-label" for=""><h4>{{course_object.teaching_level}}</h4></label>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Lecture Day:</label>
                        </div>
                        <div class="col-sm-6">
                            <label class="col-form-label" for=""><h4>{{course_object.lecture_day}}</h4></label>
                        </div>

                        <div class="row mb-3">
                            {% if course_object.students.all.count >= 25 %}
                            <div class="col-sm-12">
                                <h3>Course Is Full !</h3>
                            </div>
                            {% endif %}
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Students</label>

                                <ul>
                                    {% for student in student_object%}
                                    <li>{{student.student_name}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                            
                            

                        </div>

                    </div>
                </div>
            </div>
            <hr>
            <form action="{% url 'first_app:addStudent' course_id=course_object.id %}" method="post">
                {% csrf_token %}
                <div class="row justify-content-center">
                    <div class="col-sm-12">
                        <h3 class="text-center"> Add Student</h3>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Student Name:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="text" name="student_name" class="form-control">
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-sm-12 text-center">
                            <button type="submit" class="btn btn-primary"> Add Student</button>
                        </div>
                    </div>
            </form>





            {% if current_teacher.id == course_object.teacher.id %}
            <div class="row justify-content-start">

                <div class="col-sm-1 me-3">
                    <a class="btn btn-secondary" href="{% url 'first_app:courseEdit' course_id=course_object.id%}">edit</a>
                </div>

                <div class="col-sm-1">
                    <a class="btn btn-danger" href="{% url 'first_app:deleteCourse' course_id=course_object.id %}">Delete</a>
                </div>
            </div>
            {% endif %}


        </div>
        {% else %}
        <h1> YOU NEED To BE LOGGED IN</h1>
        {% endif %}
    </div>


</body>


</html>

Teachers&Courses/first_app/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>HOME</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(167, 170, 193, 0.707);">
    {% if teacher_session %} 
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <h4> Welcome , {{teacher_object.teacher_name}}</h4>
                    </li>
                    <li class="nav-item">
                        <form class="d-flex align-items-center">

                            <a href="{% url 'first_app:logout' %}" class="ms-3 btn btn-secondary">Logout</a>
                        </form>
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <div class="container mt-6 pt-4" style="background-color: white;">

        {% if messages %}
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <h4>  logged in  {{teacher_object.teacher_name}}</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
        {% endif %}

        <main class="pb-5">
            <div class="row justify-content-center border">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Course Name</th>
                            <th scope="col">Teaching Level </th>
                            <th scope="col">Students</th>
                            <th scope="col">Lecture Day</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for course in course_object%}
                        <tr>
                            <td><a href="{% url 'first_app:courseDetails' id=course.id %}">{{course.course_name}}</a> </td>
                            <td>{{course.teaching_level}}</td>
                            <td>{{course.students.all.count}} / 25</td>
                            <td>{{course.lecture_day}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'first_app:newCourseRedirect' %}" class="btn btn-primary btn-lg">Create a Course</a>
            </div>
            <hr>

            
        </main>
    </div>
    {% endif %}


</body>


</html>

Teachers&Courses/first_app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Index</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <div class="container mt-6 mb-3" style="background-color: white;">
        {% if messages %}
        <div class="row justify-content-center mt-3">
            <div class="col-sm-12">
                {% for massage in messages %}
                {% if massage.tags == 'error' %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <h4>Warring ! :</h4> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% if massage.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <h4>Success ! :</h4> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endif %}
        
        <div class="row"> 
            <div class="col-sm-12 text-center mt-3 mb-5 ">
                <h2>Registration</h2>
            </div>
            <div class="row justify-content-center">
                <div class="col-sm-6 ">
                    <form action="{% url 'first_app:registration' %}" method="post">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Teacher Name:</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="text" name="teacher_name" class="form-control">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Email:</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="email" name="email" class="form-control">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Password:</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="password" name="password" class="form-control">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Confirm PW:</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="password" name="conf_password" class="form-control">
                            </div>
                        </div>
                        <div class="row mb-3 justify-content-center">
                            <div class="col-sm-6 text-center">
                                <button type="submit" class="btn btn-primary">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row text-center">
                <h2 class="mt-3 mb-5">Login</h2>
            </div>
            <div class="row justify-content-center">
                <div class="col-sm-6">
                
                    <form action="{% url 'first_app:login' %}" method="post">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label for="" class="col-form-label">Email</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="email" name="email" class="form-control">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label for="" class="col-form-label">Password</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="password" name="password" class="form-control">
                            </div>
                        </div>
                        <div class="row mb-3 justify-content-center">
                            <div class="col-sm-6 text-center">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
    </div>



</body>


</html>